org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

mod_id=enchantpeak
mod_name=EnchantPeak
mod_version=1.0.0
mod_description=Shows the best enchantment combinations for diamond and netherite items via JEI/REI
mod_author=zhaojiedi1992

minecraft_version=1.21.4
fabric_loader_version=0.16.9
fabric_api_version=0.119.2+1.21.4
java_version=21

# JEI
jei_version=19.21.0.247

# REI
rei_version=16.0.783
architectury_version=13.0.10
