modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/zhaojiedi1992/enchantpeak/issues"

[[mods]]
modId = "enchantpeak"
version = "${file.jarVersion}"
displayName = "EnchantPeak"
authors = "zhaojiedi1992"
description = '''
Shows best enchantment combinations for all vanilla enchantable items in JEI.
'''
logoFile = "assets/enchantpeak/icon.png"

[[dependencies.enchantpeak]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.enchantpeak]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.3,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.enchantpeak]]
modId = "jei"
type = "optional"
versionRange = "[17.3,)"
ordering = "NONE"
side = "CLIENT"
