pluginManagement {
    repositories {
        if (settings.providers.gradleProperty('use_aliyun_mirror').map { it.toBoolean() }.getOrElse(false)) {
            maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        }
        maven { url 'https://maven.minecraftforge.net/' }
        gradlePluginPortal()
    }
}

rootProject.name = 'enchantpeak-forge7'
